param()

$ErrorActionPreference = "Stop"

$repoRoot = (& git rev-parse --show-toplevel 2>$null).Trim()
if (-not $repoRoot) { throw "Not in a git repository (run from a clone)." }

$scriptUnderTest = Join-Path $repoRoot "scripts\link-agent-files.ps1"
$expectedClaudeShim = @'
# Claude Code Compatibility Shim

This repo uses `AGENTS.md` as the canonical shared instruction file.

Before doing any work in this repo, read and follow `AGENTS.md`.

Do not edit this file. To change shared project instructions, edit `AGENTS.md`.
'@

function New-TestRepo {
    $name = "notedrop-link-agent-files-test-$([guid]::NewGuid().ToString('N'))"
    $path = Join-Path ([System.IO.Path]::GetTempPath()) $name
    New-Item -ItemType Directory -Path $path -Force | Out-Null
    Push-Location $path
    try {
        git init -q
        New-Item -ItemType Directory -Path "scripts" -Force | Out-Null
        Copy-Item -LiteralPath $scriptUnderTest -Destination "scripts\link-agent-files.ps1"
    } finally {
        Pop-Location
    }
    return $path
}

function Get-FileId {
    param([string]$Path)
    return (fsutil file queryfileid $Path)
}

function Invoke-InRepo {
    param(
        [string]$Repo,
        [scriptblock]$Script
    )
    Push-Location $Repo
    try {
        & $Script
    } finally {
        Pop-Location
    }
}

function Assert-Equal {
    param(
        $Actual,
        $Expected,
        [string]$Message
    )
    if ($Actual -ne $Expected) {
        throw "$Message`nExpected: $Expected`nActual:   $Actual"
    }
}

function Assert-NotEqual {
    param(
        $Actual,
        $Unexpected,
        [string]$Message
    )
    if ($Actual -eq $Unexpected) {
        throw "$Message`nUnexpected: $Unexpected"
    }
}

$repo = New-TestRepo
try {
    Invoke-InRepo $repo {
        Set-Content -LiteralPath "AGENTS.md" -Value "agents canonical" -NoNewline -Encoding UTF8

        .\scripts\link-agent-files.ps1 | Out-Null

        Assert-Equal (Get-Content -Raw -Encoding UTF8 "AGENTS.md") "agents canonical" "AGENTS.md must remain canonical"
        Assert-Equal (Get-Content -Raw -Encoding UTF8 "CLAUDE.md") $expectedClaudeShim "CLAUDE.md must be the compatibility shim"
        Assert-NotEqual (Get-FileId "CLAUDE.md") (Get-FileId "AGENTS.md") "CLAUDE.md must not be a hard link to AGENTS.md"
    }
}
finally {
    Remove-Item -LiteralPath $repo -Recurse -Force
}

$repo = New-TestRepo
try {
    Invoke-InRepo $repo {
        Set-Content -LiteralPath "AGENTS.md" -Value "agents canonical" -NoNewline -Encoding UTF8
        New-Item -ItemType HardLink -Path "CLAUDE.md" -Value "AGENTS.md" | Out-Null

        .\scripts\link-agent-files.ps1 | Out-Null

        Assert-Equal (Get-Content -Raw -Encoding UTF8 "AGENTS.md") "agents canonical" "AGENTS.md must survive legacy hard-link conversion"
        Assert-Equal (Get-Content -Raw -Encoding UTF8 "CLAUDE.md") $expectedClaudeShim "Legacy hard-linked CLAUDE.md must be replaced with the shim"
        Assert-NotEqual (Get-FileId "CLAUDE.md") (Get-FileId "AGENTS.md") "Legacy hard link must be broken"
    }
}
finally {
    Remove-Item -LiteralPath $repo -Recurse -Force
}

$repo = New-TestRepo
try {
    Invoke-InRepo $repo {
        Set-Content -LiteralPath "AGENTS.md" -Value "agents canonical" -NoNewline -Encoding UTF8
        Set-Content -LiteralPath "CLAUDE.md" -Value "claude divergent content" -NoNewline -Encoding UTF8

        .\scripts\link-agent-files.ps1 | Out-Null

        Assert-Equal (Get-Content -Raw -Encoding UTF8 "AGENTS.md") "agents canonical" "AGENTS.md must remain canonical when CLAUDE.md diverges"
        Assert-Equal (Get-Content -Raw -Encoding UTF8 "CLAUDE.md") $expectedClaudeShim "Diverged CLAUDE.md must be replaced with the shim"
        Assert-NotEqual (Get-FileId "CLAUDE.md") (Get-FileId "AGENTS.md") "Diverged CLAUDE.md must not become a hard link"

        $backup = Get-ChildItem -LiteralPath "." -Filter "CLAUDE.md.bak.*" | Select-Object -First 1
        if (-not $backup) { throw "Diverged CLAUDE.md was not backed up" }
        Assert-Equal (Get-Content -Raw -Encoding UTF8 $backup.FullName) "claude divergent content" "CLAUDE.md backup must preserve discarded content"
    }
}
finally {
    Remove-Item -LiteralPath $repo -Recurse -Force
}

Write-Host "link-agent-files tests passed"
